#1 patch of fixes.
oreh17/DogService pull request #3
Opened 2017-07-11 14:23 UTC by oreh17

Project with latest changes was found. Also I fixed some issues from comments

2017-07-12 14:41 UTC, korobochka requested changes
Review round 2.
You can push additional commits to the same branch `master_update` to fix the issues.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/pom.xml
> +  <artifactId>Dog-Example</artifactId>
Small letters => `dog-example`

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/pom.xml
>        <artifactId>json-simple</artifactId>
still both gson and json-simple are present, choose one

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +        DogService.incrementDogId();
This introduces two way dependency, which makes application more comples.
Ideally your Dog should know nothing about DogService.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            System.out.println("Name should has length in range 1-100. Value is not updated to next one: " + name);
exceptions

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +                System.out.println("DateOfBirth should be before current date. Value is not updated. DateOfBirth date: " + dateOfBirth + ". Current date: " + simpleDateFormat.format(new Date()));
exceptions

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +        DateFormat simpleDateFormat = new SimpleDateFormat("dd.MM.yyyy");
extract constant into static final class field

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            this.height = height;
braces around branches

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            System.out.println("Height should be positive: " + height + ". Value is not updated");
exception

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            this.weight = weight;
braces

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            System.out.println("Weight should be positive: " + weight + ". Value is not updated");
exceptions

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/json/JsonHelper.java
> +        if (jsonObject == null)
Are this null-checks important? It seems to me that if you pass `null` here it is a logical error in your program, should handle it appropriately in some other place

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/rest/DogService.java
> +public class DogService {
Here you convert method parameters from Json and responses to Json manually. There mush be a way to do this automatically: you can define function like `public Dog createNewDog(Dog dog)` and the parameters and responses will be converted by the application server.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/rest/DogService.java
> +public class DogService {
This way you will not have to set status 200 manually, for example. And if you throw exceptions in Dog setters (if not passed validation) status will be set to 500 automatically.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/main/java/com/common/rest/DogService.java
> +        JsonObject result = jobject.getAsJsonObject(id);
Ssame comments as in previous review, just get the dog from the map.
And don't forget to return 404 if no dog with such Id.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/test/java/com/common/war/DogTest.java
> +        Dog dog1 = new Dog(10, "TestName", "25.05.2010", 15, 25, true);
Usually it does not make much sense to test getters.

2017-07-12 14:41 UTC, korobochka commented on DogServiceExample/src/test/java/com/common/war/DogTest.java
> +    public void setDateOfBirthForDog() {
same comments about splitting into multiple tests

2017-07-12 15:14 UTC, oreh17 commented on DogServiceExample/pom.xml
> +  <artifactId>Dog-Example</artifactId>
changed

2017-07-12 15:15 UTC, oreh17 commented on DogServiceExample/pom.xml
>        <artifactId>json-simple</artifactId>
It's used in DogTest for assertion and @Test annotation... Substituted to:
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.4</version>
      <scope>test</scope>
    </dependency>

2017-07-12 15:16 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +        DogService.incrementDogId();
changed. incrementDogId() moved to DogService.

2017-07-12 15:17 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +        DateFormat simpleDateFormat = new SimpleDateFormat("dd.MM.yyyy");
changed

2017-07-12 15:18 UTC, anatolydyachenko commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            this.weight = weight;
Is it mandatory if there is only 1 statement after if part? Or it's some kind of patterns.

2017-07-13 09:20 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/rest/DogService.java
> +        JsonObject result = jobject.getAsJsonObject(id);
Changed

2017-08-10 12:52 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            System.out.println("Name should has length in range 1-100. Value is not updated to next one: " + name);
Done

2017-08-10 12:52 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +                System.out.println("DateOfBirth should be before current date. Value is not updated. DateOfBirth date: " + dateOfBirth + ". Current date: " + simpleDateFormat.format(new Date()));
Done

2017-08-10 12:52 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            this.height = height;
Done

2017-08-10 12:52 UTC, oreh17 commented on DogServiceExample/src/main/java/com/common/app/Dog.java
> +            System.out.println("Weight should be positive: " + weight + ". Value is not updated");
Done

2017-08-10 12:54 UTC, merged